---
title: "COMPSCIX 415.2 Homework 1"
author: "Gokila Rajaiah"
date: "February 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
My Github repository for my assignments can be found at this URL: [https://github.com/ila7goki/compscix4152](https://github.com/ila7goki/compscix4152)

```{r load_package, warning=FALSE, message=FALSE}
library(tidyverse)
library(mdsr)
```


## About WorldCities Dataset:


There are 23018 observations and 10 variables in the WorldCities dataset. Following are the 10 variables: code, name, atitude, longitude, country, countryRegion, population, regionCode, region and date.

```{r warning=FALSE, message=FALSE}
data('WorldCities')

```

```{r warning=FALSE, message=FALSE}

glimpse(WorldCities)

WorldCities <- head(WorldCities, 200)

country_col <- WorldCities$country

unique(country_col)

```

# Unique Regions

```{r warning=FALSE, message=FALSE}

WorldCities %>% select(region) %>% unique()


```


# Unique Countries

```{r Warning=FALSE, message=FALSE, tidy=TRUE}

WorldCities %>% select(country) %>% unique()
```

# Population Histogram 1

```{r message=FALSE, warning=FALSE}

WorldCities %>% ggplot(aes(x=population)) + geom_histogram(bins=25) + xlab('City Population')

```

#Population Histogram 2

```{r message=FALSE, warning=FALSE}

WorldCities %>% ggplot(aes(x=population)) + geom_histogram() + scale_x_continuous(labels = scales::comma) + xlab('City Population') + ylab('Count') + ggtitle('Histogram Plot of Population') + theme_bw()

```